version: '3.8'

services:
  database:
    container_name: calisto_mariadb.dev
    hostname: calisto_mariadb_dev
    build:
      context: .
      # dockerfile: ./docker/Dockerfile.database
    image: calisto/mariadb_dev
    #  --init-file="/script/init.sql"
    command: mysqld --sql_mode="ORACLE" --datadir=/var/lib/mysql --lower_case_table_names=1 --verbose
    ports:
      - "${MARIADB_EXPOSE_PORT}:${MARIADB_TCP_PORT}"
    # env_file:
    #   - .env.dev
    environment:
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE_NAME=$MARIADB_DATABASE_NAME
      - MYSQL_TCP_PORT=$MARIADB_TCP_PORT
      - TZ=America/Sao_Paulo
    volumes:
      - ${MARIADB_DATA_PATH:-mariadb}:/var/lib/mysql

volumes:
  mariadb:
    external: false